### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "password": "123456",
    "name": "tv1411",
    "phone": "0123456787",
    "role": "USE",
    "email": "tv1411@gmail.com"
}

### Login
POST http://localhost:5000/api/auth/signin
Content-Type: application/json

{
    "password": "123456",
    "phone": "0123456788"
}

### Insert
POST http://localhost:5000/api/insert/roles
Content-Type: application/json